### ISSUE TITLE
请问如何抓取更多的条数？

### ISSUE THREAD

**Issue by papiJohn** [zgq354/weibo-rss#1]
如题，顺便感谢作者！

**Comment by zgq354** [comment]
RSS的话主要目的是获取最新更新，所以对条数并不会十分敏感。关于抓取最近微博的接口调用在 /common/weibo.js 的 38行左右，这里调用的接口没有条数的设置，得多传入一个page参数这样才能抓到其他的页，然后把这几页的数据整合在一起就好了。
