### ISSUE TITLE
外部链接的图标没有去掉

### ISSUE THREAD

**Issue by DerekTso** [zgq354/weibo-rss#10]
rss:
`https://api.izgq.net/weibo/rss/1660079292`

![image](https://user-images.githubusercontent.com/10363328/39968499-3dbd4cae-5700-11e8-8c6c-d8184631a0bb.png)

**Comment by zgq354** [comment]
已修复～

**Comment by DerekTso** [comment]
this problem happened again
**rss url:**
[https://api.izgq.net/weibo/rss/1627825392](https://api.izgq.net/weibo/rss/1627825392)

![image](https://user-images.githubusercontent.com/10363328/41698437-fa3cc828-7550-11e8-967b-37a97be65578.png)

**Comment by zgq354** [comment]
已修复，若API数据再次发生变化，则问题会再次出现
