### ISSUE TITLE
某个微博抓取失败

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [zgq354/weibo-rss#11]
https://weibo.com/u/1855501681?profile_ftype=1&is_all=1#_0
抓取的地址是：

https://api.izgq.net/weibo/rss/1855501681

**Comment by zgq354** [comment]
问题出现在 https://m.weibo.cn/status/4239660991131872 这条微博，这是条纯图片微博，文字属性为 null ，接下来对其进行字符串替换的操作因为null而产生了报错
