### ISSUE TITLE
微博抓取失败

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [zgq354/weibo-rss#15]
https://api.izgq.net/weibo/rss/1195054531

**Comment by zgq354** [comment]
经过测试发现程序本身没有问题，是目前的demo站点的访问量过高，任务队列长时间占满导致部分请求抓取失败，建议自行搭建

**Comment by zgq354** [comment]
这时候需要考虑一下高并发请求时任务队列的优化问题

**Comment by DerekTso** [comment]
添加一个
[https://api.izgq.net/weibo/rss/3209967147](https://api.izgq.net/weibo/rss/3209967147)
![image](https://user-images.githubusercontent.com/10363328/42729958-e60d88b4-881b-11e8-8d2e-7f957938fefd.png)

**Comment by DerekTso** [comment]
it seems the service was down
![image](https://user-images.githubusercontent.com/10363328/43295516-fe2ea9e0-9177-11e8-8880-e7312e7edfe0.png)
