### ISSUE TITLE
Docker部署时CONTAINER ID填什么？

### ISSUE THREAD

**Issue by jozhn** [zgq354/weibo-rss#17]
`docker run -p 3000:3000 -d --name weibo-rss --restart=always [CONTAINER ID]`
没学过nodejs和docker，不懂啊~

**Comment by jozhn** [comment]
原来应该是IMAGE ID啊

解决办法：
- build之后输入`docker images`查看image列表
- 复制weibo-rss那个image id替换下面的IMAGE ID然后运行下面的命令即可
`docker run -p 3000:3000 -d --name weibo-rss --restart=always [IMAGE ID]`

另：
开放3000端口即可通过ip访问，用nginx反代可实现域名访问，暂时还没尝试，成功了再来补充。

**Comment by jozhn** [comment]
分享一下nginx配置文件，下面代码放到`server()`中即可完成反向代理
```
		location /weibo/{
			proxy_pass http://127.0.0.1:3000/;
		}
```

**Comment by zgq354** [comment]
oh，Wiki写的不够详细，不好意思，晚点我再补充
