### ISSUE TITLE
无法获取原图

### ISSUE THREAD

**Issue by gagqgs** [zgq354/weibo-rss#19]
rt，图片变糊了

**Comment by zgq354** [comment]
因为考虑到手机阅读器直接加载原图对流量和带宽消耗比较大，信号不好的地方体验不佳，所以上一次的提交默认显示了小图，点击小图就可以跳转到原图的链接了

**Comment by vvyoko** [comment]
@zgq354 
可以带一些参数吗？比如说原图与否，原创与否？
原图与否是因为个人需要原图。
原创的话应该可以很大的缓解服务器压力吧。
很多微博差不多90%都是转发，只看原创的抓取频率应该会降低很多吧。
我用的inoreader貌似是自动设置抓取频率的，更新频率大就会频繁抓取，如果频率不大抓取次数也会减少很多。_

**Comment by zgq354** [comment]
原图方面的参数这个可以考虑😃
因为目前是每一条新微博都会抓取完整的详情来拼接全文和准确的时间信息，来达成比较好的阅读体验，和原创与否没什么关系。所以继续这个方式的话，可能解决办法是加IP地址负载均衡了。

**Comment by ivysrono** [comment]
需要原图+1

**Comment by MZLAKg2aGGFs8yi** [comment]
原图+1，大部分手机端软件都能设置只在wifi下下载图片的，并不需要画蛇添足的转成小图。

**Comment by zgq354** [comment]
各位觉得默认显示原图好呢还是先显示小图再显示原图比较好，准备增加一个参数配置

**Comment by ivysrono** [comment]
默认原图

**Comment by gagqgs** [comment]
默认原图吧

**Comment by zgq354** [comment]
已经更新～默认输出原图，在订阅链接后加上参数 `?largePic=0` 即可切换为小图显示

完整例子：
```
https://api.izgq.net/weibo/rss/2803301701?largePic=0
```

**Comment by DerekTso** [comment]
@zgq354 not sure if the current change for original image, at this time, some feeds are showing "No title" as feed title.
