### ISSUE TITLE
无法显示全文

### ISSUE THREAD

**Issue by DerekTso** [zgq354/weibo-rss#20]
e.g.
![image](https://user-images.githubusercontent.com/10363328/44182273-db0b6e00-a138-11e8-9b48-46b3e825c805.png)

**Comment by zgq354** [comment]
因为以前有的微博在未登录的情况下是获取不到全文的，以往的策略是直接丢弃这条微博，丢失了一部分信息，在 [这个提交](https://github.com/zgq354/weibo-rss/commit/c95763cabb06db062eb91f3e1b98a0d2d2d87efd) 增加了若获取不到全文则显示原始的不带全文的内容的策略。

**Comment by zgq354** [comment]
![screenshot](https://user-images.githubusercontent.com/9024954/44205029-94913000-a187-11e8-9143-55b22f8440b3.png)

这种微博的全文在未登录的情况会有这样的返回

也是一种很无奈的情况-_-

**Comment by DerekTso** [comment]
理解了, 谢谢
