### ISSUE TITLE
转发微博的图片信息丢失问题

### ISSUE THREAD

**Issue by DerekTso** [zgq354/weibo-rss#22]
**weibo 中的显示**
![image](https://user-images.githubusercontent.com/10363328/45249770-b03bc080-b358-11e8-8deb-58bcc11c9c9b.png)

---

**rss 中的显示**
![image](https://user-images.githubusercontent.com/10363328/45249782-eb3df400-b358-11e8-9e7a-4cfa40200461.png)

**rss feed**
[weibo rss feed](https://api.izgq.net/weibo/rss/1627825392)

**Comment by DerekTso** [comment]
Also, it didn't show the video info for rss feed item:

* rss feed view

![image](https://user-images.githubusercontent.com/10363328/45685199-30450000-bb7b-11e8-8ee8-4337a0c1c6c3.png)

* weibo post view

![image](https://user-images.githubusercontent.com/10363328/45685220-46eb5700-bb7b-11e8-8397-79c2a64d81dc.png)

**Comment by zgq354** [comment]
很奇怪，我自己转发了这条微博，没有出现问题。
![image](https://user-images.githubusercontent.com/9024954/47613967-f4cf1700-dad2-11e8-8f07-418ac7617464.png)

**Comment by DerekTso** [comment]
I subscribe this [rss feed](https://api.izgq.net/weibo/rss/1627825392) and view it on inoreader, the hyper link info / video link info etc still missing.

But, rss feed is ok, maybe this is the issue of inoreader, it removes those text of the hyper links.

![image](https://user-images.githubusercontent.com/10363328/47663190-6d1f0080-dbd7-11e8-99b0-7228fd2b2a47.png)

* how it shows on inoreader

![image](https://user-images.githubusercontent.com/10363328/47662505-01886380-dbd6-11e8-9d89-e5ef5eae6eb8.png)


![image](https://user-images.githubusercontent.com/10363328/47662626-3dbbc400-dbd6-11e8-94dc-0d8089e34d7d.png)

* how it shows on inoreader by source code

the hyper link text "网页链接" was removed as showed below:

![image](https://user-images.githubusercontent.com/10363328/47663171-5ed0e480-dbd7-11e8-8558-692ed9d0c4c2.png)

**Comment by DerekTso** [comment]
@zgq354 I checked on Reeder, it's ok. 99% is the issue from inoreader.
thanks for your time
