### ISSUE TITLE
关注某微博失败了

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [zgq354/weibo-rss#23]
https://www.weibo.com/527745646?profile_ftype=1&is_all=1#_0

关注此微博失败

**Comment by Mr-Phone** [comment]
https://api.izgq.net/weibo/rss/2398996905
具体是什么表现？

**Comment by Mr-Phone** [comment]
https://api.izgq.net/weibo/rss/2398996905
能正常关注
你说的失败具体是什么表现？

**Comment by MZLAKg2aGGFs8yi** [comment]
把这个url贴到https://api.izgq.net/weibo/点订阅会返回数据获取失败

**Comment by Mr-Phone** [comment]
你的链接不包含微博内部的ID。
如果是chrome 建议你：
1、在博主个人页面点右击，选择【检查】
2、在控制台点选【Console】卡片
3、输入【/uid=(\d+)/. exec(document.querySelector('.opt_box .btn_bed').getAttribute('action-data'))[1]】回车
获得博主ID。
再使用链接：https://api.izgq.net/weibo/rss/ID

**Comment by zgq354** [comment]
因为微博的UID是10位的，之前做过短的数字链接的转换，现在有可能是这种转换方式失效了，我检查一下

**Comment by zgq354** [comment]
发现微博手机版已经修复了这个问题，原本的UID转换方案也失效，用不上了，换回以前的方案，目前工作应该是正常的
