### ISSUE TITLE
微博没有更新时lastBuildDate也更新了

### ISSUE THREAD

**Issue by jozhn** [zgq354/weibo-rss#28]
我觉得微博内容没变时，是否应该不更新lastBuildDate标签中的时间呢？

**Comment by zgq354** [comment]
没弄错的话，lastBuildDate 是指这个feed的生成时间，针对的是这个feed，在RSS 2.0的定义里面有说
https://stackoverflow.com/questions/1698076/what-is-the-difference-between-pubdate-and-lastbuilddate-in-rss

程序默认会将生成的feed缓存15分钟，所以15分钟之内看到的lastBuildDate应该是一样的~

**Comment by jozhn** [comment]
嗯嗯，谢谢
