### ISSUE TITLE
获取微博时间间隔

### ISSUE THREAD

**Issue by FFFcat** [zgq354/weibo-rss#29]
请问一下获取的间隔是多久…还有能不能把间隔变长或变短？自己搭建的…不怕服务器资源不够。

**Comment by zgq354** [comment]
默认15分钟。
在这儿 `weibo-rss/routes/rss.js` 可以修改。

**Comment by FFFcat** [comment]
好的，谢谢作者。还想问一个问题，请问UID储存在哪个文件？还是没有进行储存的？

**Comment by zgq354** [comment]
不会保存的，缓存过一段时间会自动清理

**Comment by FFFcat** [comment]
OK，谢谢作者
