### ISSUE TITLE
谢谢zgq354 请问怎么增加rss里面显示的微博的条数呢？想备份一下自己的微博

### ISSUE THREAD

**Issue by sealionking** [zgq354/weibo-rss#31]
我之前用RSSHub，但是那个对于长微博和多图支持得不不是很好。
用了这个之后发现支持的很好。
所以想请问，有没有办法使得rss里提取的微博条数增加呢？
我是用docker compose 部署的

**Comment by zgq354** [comment]
RSS主要还是通过按一定频率请求最近几条微博来实现微博的更新的，所以程序默认只会请求第一页的数据，需要更多的话可能要自己参考源码另外写个脚本来实现导出~

**Comment by sealionking** [comment]
不会写代码 o(╯□╰)o

**Comment by zgq354** [comment]
可以试一试

**Comment by sealionking** [comment]
好的，这个算是什么语言来写啊
