### ISSUE TITLE
Added a `Deploy to Heroku Button` feature to this repo

### ISSUE THREAD

**Issue by huan** [zgq354/weibo-rss#34]
Hi zgq354,

I'd like to say thank you first for your great work, I had been using your API server for years.

However it's too slow now, so I created my own Heroku Dyno today, it works great.

In order to deploy to Heroku easy, I added a button to the readme, you can have a look at here:
https://github.com/huan/weibo-rss

I can make a PR if you like.

Best,
Huan

**Comment by zgq354** [comment]
Sorry for the delay in response. Because of the large concurrency and restrictions on Weibo, the service under api.izgq.net is currently so slow.

I'm glad to see more people using it conveniently. One-click deployment is really awesome!

Feel free to make a PR!

**Comment by huan** [comment]
PR-ed.

**Comment by zgq354** [comment]
Merged.
