### ISSUE TITLE
Improve the power of our official service

### ISSUE THREAD

**Issue by huan** [zgq354/weibo-rss#36]
Currently the <https://api.izgq.net/weibo/> is very slow and almost not useable.

What's the current compute resource it using? Does it use Heroku?

I have some Heroku resources, and if you can provide a Dyno requirement of the service, I might be able to donate some in the following months.

Please feel free to let me know what Dyno will back our service to be stable and availble.

Huan.

**Comment by zgq354** [comment]
The current service runs on a vps instance provided by Tencent Cloud, with a monthly fee of ¥1 for student discounts.

The reason for the slow speed is that there are too many Weibo subscriptions. Even if there is a good working cache, the frequency of requests from the program to Weibo is still very high, which maybe exceeded the single IP limit of Weibo. Therefore, the anti-reptile mechanism of Weibo will be triggered during the peak period.

I did a simple analysis, and the access was denied during these time periods. ("418" is the status returned when rejected by Weibo)

![image](https://user-images.githubusercontent.com/9024954/56965608-434b9400-6b90-11e9-8331-2146e752ac98.png)

Maybe we can design a load balancing mechanism based on weibo uid to distribute traffic to multiple instances with different IP addresses.
