### ISSUE TITLE
微博更新了rss没有更新

### ISSUE THREAD

**Issue by FFFcat** [zgq354/weibo-rss#37]
用docker部署的，其他都正常，某个人的微博过了几个月发了一条微博，RSS收不到，重启docker也没用。。请问可以删掉他的xml然后再获取吗？还是有其他的解决方法？

**Comment by zgq354** [comment]
可以检查一下手机版未登录的情况下能不能在他的主页发现这条微博，默认是15分钟更新一次的，所以不需要删除。

**Comment by FFFcat** [comment]
是可以看的…可能是对方太久没更新了吧。。
