### ISSUE TITLE
自己部署的端口问题

### ISSUE THREAD

**Issue by luklitwai** [zgq354/weibo-rss#39]
想请问一下自己部署后，pm2也设置好了，网页在线但是浏览器输入部署程序ip：3000端口显示拒绝。此外在哪里可以更改端口？

**Comment by zgq354** [comment]
有可能是防火墙拦截？试试在服务器用访问 127.0.0.1:3000

更改端口的话，通过环境变量 PORT 启动就可以了，或者是用nginx的proxy_pass指令转发

**Comment by luklitwai** [comment]
> 有可能是防火墙拦截？试试在服务器用访问 127.0.0.1:3000
> 
> 更改端口的话，通过环境变量 PORT 启动就可以了，或者是用nginx的proxy_pass指令转发

我试一下，因为当时我防火墙3000端口开了还是拒绝，可能是端口冲突？

**Comment by luklitwai** [comment]
> 有可能是防火墙拦截？试试在服务器用访问 127.0.0.1:3000
> 
> 更改端口的话，通过环境变量 PORT 启动就可以了，或者是用nginx的proxy_pass指令转发
你好，目前是已经起来了，但是如何更换端口呢？是在process.json里面将PORT改为其他端口吗？

**Comment by luklitwai** [comment]
你好，目前是已经起来了，但是如何更换端口呢？是在process.json里面将PORT改为其他端口吗？

**Comment by luklitwai** [comment]
原来在bin/www 里面修改，我看到了。修改好了，非常感谢您。
