### ISSUE TITLE
如何通过docker搭建

### ISSUE THREAD

**Issue by DerekTso** [zgq354/weibo-rss#4]
尝试git clone项目下来,直接"docker build ." 会报错
standard_init_linux.go:195: exec user process caused "exec format error"

nodejs version: 8.9.4

**Comment by zgq354** [comment]
这里有一个挺详细的教程
https://blog.liuwm.work/posts/6a3c/#more

有空我更新一下搭建的方法 :D

**Comment by DerekTso** [comment]
好的.
我看了这个教程, 我在树莓派上运行run了redis和weiborss两个docker container, 不过, 有关redis 环境变量的东西还是不太理解
```
ENV REDIS_PORT_6379_TCP_ADDR ${REDIS_PORT_6379_TCP_ADDR}
ENV REDIS_PORT_6379_TCP_PORT ${REDIS_PORT_6379_TCP_PORT}
ENV REDIS_PASSWORD ${REDIS_PASSWORD}
```
${REDIS_PORT_6379_TCP_ADDR} 是设置为本地地址吗(e.g. 192.168.x.x, 如果没有外网域名的话)?
${REDIS_PORT_6379_TCP_PORT} 是设置为redis 的端口号6379 还是映射的端口号呢?
${REDIS_PASSWORD} 如果没有设置redis password的话, 这一行是不是可以删除呢?

谢谢你的教程, 期待搭建的方法~

**Comment by zgq354** [comment]
@DerekTso 不好意思，前段时间忙着考试忘记了回复，环境变量的问题的话，这几个变量主要还是用来传递redis的连接信息，所以要保证的是运行服务的容器能够连接上Redis容器

由于Redis在数据量大了的时候内存占用巨大，因此，目前最新的版本的缓存部分我已经把Redis换成LevelDB，LevelDB在Node里面可以直接集成，就不用另外部署容器了，部署起来可以更简便一些

**Comment by DerekTso** [comment]
@zgq354 没关系。我调试不成功reddis，所以直接跑的nodejs，算是成功了。不过，如果你有时间的话，我还是挺期待你的部署方案的。

**Comment by zgq354** [comment]
现在的最新版本已经不需要Redis啦，我的部署方案其实也差不多，只是用 Daocloud 来帮助管理 Docker 容器的部署，然后配置了一下Nginx把 api.izgq.net/weibo 下的请求反向代理转发到了程序的端口而已

**Comment by DerekTso** [comment]
好的。Docker还不是太熟悉，我再去了解一下。谢谢啦~
