### ISSUE TITLE
rss连接返回User Not Found

### ISSUE THREAD

**Issue by mengdodo** [zgq354/weibo-rss#40]
麻烦看下,已知直接访问ID的连接会跳转别名

![image](https://user-images.githubusercontent.com/21698573/63273432-857c1b00-c2d0-11e9-93d4-e92d0d6e0353.png)

访问别名时
![image](https://user-images.githubusercontent.com/21698573/63273280-46e66080-c2d0-11e9-9755-89c804d28e59.png)

访问ID时
![image](https://user-images.githubusercontent.com/21698573/63273354-6a111000-c2d0-11e9-92c1-61176a184731.png)

**Comment by zgq354** [comment]
微博限制了一部分用户在未登录状态下的访问，暂时无法解决
