### ISSUE TITLE
个别微博无法抓取rss

### ISSUE THREAD

**Issue by lee2333** [zgq354/weibo-rss#44]
例如这个，https://weibo.com/shenshaopeng?topnav=1&wvr=6&topsug=1&is_all=1
有的就没有问题，请问是新浪屏蔽掉了还是什么原因？

**Comment by zgq354** [comment]
个性域名解析的问题，拿到UID之后应该还是可以的
https://rssfeed.today/weibo/rss/1677241611

**Comment by lee2333** [comment]
谢谢，这个链接我在feedme里成功添加上了，在freedly中不知道为什么还是订阅不了
