### ISSUE TITLE
Inoreader不能显示图片

### ISSUE THREAD

**Issue by visayafan** [zgq354/weibo-rss#46]
手机APP上一切正常，但在电脑网页端图片全部不能显示，这怎么解决呢？

**Comment by zgq354** [comment]
因为微博的图片链接做了反盗链验证，会根据来源头部的 referer 来限制加载，而浏览器请求图片默认会发送 inoreader 的referer，暂时没什么很好的办法处理。

**Comment by visayafan** [comment]
前段时间发现了个油猴插件把这个问题解决了，叫 [Display anti-hotlinking images For Inoreader](https://greasyfork.org/zh-CN/scripts/376884-%E6%98%BE%E7%A4%BA%E9%98%B2%E7%9B%97%E9%93%BE%E5%9B%BE%E7%89%87-for-inoreader)
