### ISSUE TITLE
个性化域名无法解析的问题

### ISSUE THREAD

**Issue by laoluo8** [zgq354/weibo-rss#47]
当要转换的用户的域名为**个性化域名**的时候，会报错，比如：
<img width="1392" alt="截屏2020-03-11下午8 54 46" src="https://user-images.githubusercontent.com/44857747/76419015-9ca06880-63da-11ea-8414-06a4c8107fe3.png">

关于**微博个性化域名**：
<img width="826" alt="截屏2020-03-11下午8 58 39" src="https://user-images.githubusercontent.com/44857747/76419324-19cbdd80-63db-11ea-9512-2687b6b6010b.png">

**Comment by zgq354** [comment]
嗯，之前基于手机版跳转实现的个性域名转换的逻辑失效了，接下来打算利用海外版来做
https://m.overseas.weibo.com/user/kaifulee

**Comment by kiyoakila** [comment]
关于这个，可以在这个人的一条微博下-关于这个，可以在这个人的一条微博下-评论-查看更多，打开一个新页面后可以在url里面看到微博id号，然后这个id号是可以解析的。

**Comment by zgq354** [comment]
已修复，不是程序的问题，是线上 Demo 的配置出错了 = =
