### ISSUE TITLE
某些博主不能生成订阅

### ISSUE THREAD

**Issue by Alphabet1226** [zgq354/weibo-rss#48]
试了好几个，唯独这位博主无法生成订阅
https://rssfeed.today/weibo/rss/529645621
![image](https://user-images.githubusercontent.com/51783873/94453295-16673a80-01e3-11eb-943c-3729dde298f0.png)

**Comment by zgq354** [comment]
链接应该是这个，应该是比较老的博主，uid比较短
https://rssfeed.today/weibo/rss/1251560221

**Comment by sunkint** [comment]
https://weibo.com/doraemonstx
