### ISSUE TITLE
会遗漏文章

### ISSUE THREAD

**Issue by 10362227** [zgq354/weibo-rss#49]
RSS地址：https://rssfeed.today/weibo/rss/2698087403
比如第二条博文rss就没有显示。主页：https://weibo.com/u/2698087403?profile_ftype=1&is_all=1#_0

这个问题很早发现了，概率不高，如果某个博主更新频率很高，一天总会发现一两条遗漏

**Comment by zgq354** [comment]
主要是这里每一次都只会拉第一页的微博，服务器压力大的时候，缓存时间也比较长一些，对更新频率有更高要求的话，最好自己搭建

**Comment by 10362227** [comment]
> 主要是这里每一次都只会拉第一页的微博，服务器压力大的时候，缓存时间也比较长一些，对更新频率有更高要求的话，最好自己搭建

不是这个意思，就是rss会遗漏文章，一个bug，有些文案就是不会显示，我把这种遗漏的文章文案复制，用自己的号发布，也一样不会显示。

**Comment by 10362227** [comment]
@zgq354 能搞下吗

**Comment by 10362227** [comment]
@zgq354 哦 我搞定了，是游客不能看到一些特定文案的微博，添加cookie就可以了

**Comment by aloasut** [comment]
> @zgq354 哦 我搞定了，是游客不能看到一些特定文案的微博，添加cookie就可以了

请问如何添加cookie？ 我发现一些粉丝可见的看不到。

**Comment by zgq354** [comment]
> > @zgq354 哦 我搞定了，是游客不能看到一些特定文案的微博，添加cookie就可以了
> 
> 请问如何添加cookie？ 我发现一些粉丝可见的看不到。

后面可以支持下请求的配置
