### ISSUE TITLE
RSS Feed Issue

### ISSUE THREAD

**Issue by DerekTso** [zgq354/weibo-rss#5]
有些微博的RSS用着用着就出错了，比如 https://api.izgq.net/weibo/rss/2145376602

Error Info:

There are issues with this feed. Please check it and resubscribe if necessary.

> This XML document is invalid, likely due to invalid characters. XML error: Not well-formed (invalid token) at line 1, column 1

**Comment by zgq354** [comment]
在未登录的情况下无论电脑还是手机打开这个id的微博主页也是显示一片空白，结合最近的错误记录，似乎weibo对某些帐号限制了公开访问
![image](https://user-images.githubusercontent.com/9024954/36294398-6f2242be-131b-11e8-9348-6c8f4ea5602a.png)

**Comment by DerekTso** [comment]
还是同样一个问题，最近发现，我之前弄的好些RSS慢慢的都失效了。
我尝试换了另一个RSS的链接，用同样一个用户的ID，却是有效的
所以我猜想，这应该不是weibo的问题吧? 谢谢
https://api.izgq.net/weibo/rss/2145376602（失效）
https://api.prprpr.me/weibo/rss/2145376602（有效）

**Comment by zgq354** [comment]
两个项目的RSS的来源是不一样的，DIYGod的版本来自于微博秀组件，本项目是抓取微博手机版，微博秀有一个问题是本身获取的信息不是完整的，所以我这里没有使用它。失效主要还是微博限制了公开访问，未来得考虑一下怎么把各个源头的信息整合起来

**Comment by DerekTso** [comment]
明白了。
那个RSS源有一点不好的是Column View的时候，它会显示表情的图片，阅读体验不太好。
期待信息源的整合，谢谢
