### ISSUE TITLE
自建服务器生成rss时提示“数据获取失败”

### ISSUE THREAD

**Issue by terryxuwen** [zgq354/weibo-rss#51]
![image](https://user-images.githubusercontent.com/20849822/115021056-0ba99400-9eee-11eb-9ddc-125bd79f0c9e.png)

生成服务器的做法是这样的：
系统是centos 7 
运行docker run -d --restart=always  -p 5006:3000 --name weibo-rss    einverne/weibo-rss
访问 192.168.1.130:5006 后，界面正常。但是输入微博主页地址时，提示数据获取失败。

请问有解决办法吗？ 另外，有没有什么地方可以设置抓取的频度呢

**Comment by zgq354** [comment]
抓取频度取决于阅读器，程序会提供一个缓存时间
数据获取失败有可能是这个博主本身不支持，微博自己有些奇怪的策略
