### ISSUE TITLE
请问想实现对知乎的同样功能可行吗

### ISSUE THREAD

**Issue by f-reeeeee** [zgq354/weibo-rss#54]
期待大佬能做个类似的知乎的。 
（另外目前用这个追踪微博用了好久， 的确是赞，辛苦作者维护了)

**Comment by zgq354** [comment]
可以关注这个噢
https://github.com/DIYgod/RSSHub

**Comment by SiqingYu** [comment]
知乎RSS可以使用这个网站：
https://rss.lilydjwg.me/
