### ISSUE TITLE
订阅的weibo图片都失效了，怀疑是sina改了外链。

### ISSUE THREAD

**Issue by leoneoo** [zgq354/weibo-rss#57]
类似的图片链接全部失效了。https://wx2.sinaimg.cn/mw1024/008gUigsgy1h8f6bdk42zj30lk0g6grp.jpg  

下面的文章提及过类似的情况，能否解决一下这个问题！！

https://zmingcx.com/sina-micro-album-address.html

**Comment by i-iooi-i** [comment]
![image](https://user-images.githubusercontent.com/1827701/204318641-b3784c08-c9a0-4b62-a750-075b9f59349d.png)

嗯嗯, 也遇到了相同的问题, 在TTRSS里面订阅的博客, 图都变叉叉了. 🥲

**Comment by zgq354** [comment]
最近可能不太有精力投在这里，欢迎 PR :P

**Comment by i-iooi-i** [comment]
更新了最新的RSSHUB又恢复如常了，可以显示图片了。 😄

**Comment by zgq354** [comment]
一个解决思路是：在阅读器层面请求图片时带上 weibo 的 referrer （目前发现 mac / iOS 下的 Reeder 是支持的），暂时先 close 了
