### ISSUE TITLE
关于 weibo-rss 项目接下来的方向

### ISSUE THREAD

**Issue by zgq354** [zgq354/weibo-rss#58]
目前部署的公共的 weibo-rss 订阅源转换服务（[https://rssfeed.today/weibo/](https://rssfeed.today/weibo/)）已不堪重负，且当前的运营模式不太可持续。考虑到我工作后难有精力放在这块，加之其中可能的潜在风险（与当前正在走下坡路、逐渐缩紧和封闭的微博的利益冲突），公共的订阅源转换服务不再继续维护。
 
在项目的目标和定位上，也许它还可以作为一个技术玩具而继续迭代，业务层面由使用者自行维护和负责。

关于进一步的迭代方向，我希望尽可能让部署足够简单方便，资源占用尽可能少，适应 self-hosted 的状态。学习成本上，可能还会存在一定的门槛，但相信对愿意折腾 RSS 阅读器的朋友而言，这里的障碍应该问题不大。一个侧重点也是，尽量把上手曲线控制得平缓一些。

希望这个过程，能让使用者顺便收获一部分 Web 的实用知识，还有在网络连接之下，开放、共享的本来模样。
 
这是我写的第一个 Node.js 服务，至今已有五年，伴随着我在 Web 开发方向的一路成长，非常开心它能发光发热陪伴大家 ❤️

**Comment by linep47** [comment]
感谢开发者这些年来的无私付出

**Comment by zgq354** [comment]
> 感谢开发者这些年来的无私付出

哈哈，仔细想想好像也不太算“无私”吧，写代码本身也带来很多快乐和成就感啦，顺便有些副产物输出～

**Comment by csxA1** [comment]
通过[docker部署](https://github.com/zgq354/weibo-rss/wiki/Linux%E7%8E%AF%E5%A2%83%E4%B8%8B%E7%9A%84%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95#%E4%BD%BF%E7%94%A8-docker-compose-%E4%B8%80%E9%94%AE%E9%83%A8%E7%BD%B2)已经很方便了

**Comment by zgq354** [comment]
> 通过[docker部署](https://github.com/zgq354/weibo-rss/wiki/Linux%E7%8E%AF%E5%A2%83%E4%B8%8B%E7%9A%84%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95#%E4%BD%BF%E7%94%A8-docker-compose-%E4%B8%80%E9%94%AE%E9%83%A8%E7%BD%B2)已经很方便了

也是，主要是在此之外还有一系列的流程，类似域名和证书配置等等

**Comment by asdyyx1** [comment]
能不能加个cookie的设置，这样就能看到仅粉丝可见的了

**Comment by zgq354** [comment]
理论上可以

**Comment by fulixyz** [comment]
好像已经生效了
