### ISSUE TITLE
订阅特定微博不成功

### ISSUE THREAD

**Issue by wubei7231** [zgq354/weibo-rss#7]
订阅这个微博 一直不成功。https://weibo.com/acumon  其他人的微博正常。

**Comment by zgq354** [comment]
目前发现 weibo.com/acumon 在未登录的情况下是访问不了的，最近也在计划通过其它途径获取微博

**Comment by zgq354** [comment]
最新的commit中已解决这个问题，订阅 https://weibo.com/1269043140 即可

**Comment by wubei7231** [comment]
我更新试试。感谢。
